# **1) To study and implement NumPy Library**

To check which version of numpy

In [1]:
import numpy as np  #np-object of numpy
print(np.__version__)

2.0.2


Creation of array

In [2]:
arr=np.array([1,2,3,4])
print(arr[0])
print(arr[2] + arr[3])

1
7


Creation of Two-dimentional array(Matrix)

In [3]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("2nd element on 1st row: ",arr[0,1])
print("2nd row third coloum: ",arr[1,2])
#print(arr[2,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2
2nd row third coloum:  8


Define the type of array

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Array Slicing

In [5]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


To know the datatype of elements inside array

In [6]:
arr=np.array([1,2,3,4])
print(arr.dtype)
#note 64 represent bits

int64


In [7]:
ar=np.array(['apple','banana','cherry'])
print(ar.dtype)

<U6


To Make copy , change the original array, and display both arrays:

In [8]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

#change wont reflect in copied array(different memory allocation)

[42  2  3  4  5]
[1 2 3 4 5]


To Make a view , change the original array,and display both arrays:

In [9]:
ar=np.array([1,2,3,4,5])
x=ar.view()
ar[0]=42
print(ar)
print(x)

#change will reflect in the original array(same memory allocation)

[42  2  3  4  5]
[42  2  3  4  5]


The `shape` attribute of a NumPy array returns a tuple representing the dimensions of the array. The elements of the tuple give the lengths of the corresponding array dimensions.

In [10]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr1=np.array([[1,2,3,4],[5,6,7,8],[1,3,5,3]])
print(arr.shape)
print(arr1.shape)

(2, 4)
(3, 4)


In [11]:
s=np.array([1,2,3,4])
print(s.shape)

#For a one-dimensional array, the shape attribute returns a tuple with a single element, representing the number of elements in the array.

(4,)


NumPy array with a specified number of dimensions:

---
 The ndmin=5 argument is crucial here – it specifies that the resulting array should have at least 5 dimensions. NumPy adds leading dimensions of size 1 until the desired number of dimensions is reached.


In [12]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of the array :',arr.shape)

[[[[[1 2 3 4]]]]]
shape of the array : (1, 1, 1, 1, 4)


To print the array and know the type of array

In [13]:
import numpy as np
a=np.array([(1,2,3),(3,4,4)])
print(a)
print(type(a)) # type of the array

[[1 2 3]
 [3 4 4]]
<class 'numpy.ndarray'>


In [14]:
b=np.array([1,2,3])
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


To know the data types of the elements in an array

In [15]:
print(b.dtype)

int64


To Get Dimensions(Number dimensions) of the array

.ndim is an attribute in NumPy and pandas that returns the number of dimensions of an array or a DataFrame. It is a property, not a function, so you don't use parentheses with it.
* A scalar has 0 dimensions (.ndim returns 0).
* 1D array or a pandas Series has 1 dimension (.ndim returns 1)
* 2D array or a pandas DataFrame has 2 dimensions (.ndim returns 2)
* This attribute is useful for quickly checking the shape and structure of a dataset.

In [16]:
print(a.ndim)
print(b.ndim)

2
1


To get number of rows and columns in an array


In [17]:
print(a.shape) # ndim and shape are properties of an array
print(b.shape)

(2, 3)
(3,)


**dtype** specifies the data type of elements in a NumPy array, controlling memory and ensuring consistency.

In [18]:
a.dtype

dtype('int64')

if we want to specify the size of it,we can while decalring the array

In [19]:
a=np.array([(1,2,3),(3,4,4)],dtype='int16')
print(a.dtype)

int16


To get itemsize (in bytes)

*   .itemsize is a NumPy and pandas attribute that returns the size in bytes of each element in an array or DataFrame.



In [20]:
print(a.itemsize)

#An int16 integer uses 16 bits of memory, which is equal to 2 bytes. Therefore, this line will print 2.

2


In [21]:
#if i increase the dtype size to int32,i will get itemsize as
a=np.array([(1,2,3),(3,4,4)],dtype='int32')
print(a.itemsize)

4


To know how many elements present in the array

In [22]:
print(a.size)

# Looking at the previous cells, the array a was defined as a 2x3 matrix np.array([(1,2,3),(3,4,4)]). This matrix has 2 rows and 3 columns, so the total number of elements is 2 * 3 = 6.

6


To get total size/number of bytes of an array

In [23]:
print(a.size*a.itemsize)
print(a.nbytes)

24
24


To generate numbers in an array without Typing them in order

In [24]:
# NumPy array with a sequence of numbers
w=np.arange(start=1,stop=10,step=2) # OR np.arange(1,10,2)
print(w)

#The sequence will go up to, but not include, 10

[1 3 5 7 9]


To print an array and its no.of rows and columns

In [25]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


For accessing a specific element[r,c]

In [26]:
print(a[1,4])
a[0,-1] # through negative indexing

12


np.int64(7)

 For accessing a complete row or coulumn

In [27]:
print(a[1,:])
print(a[:,5])

[ 8  9 10 11 12 13 14]
[ 6 13]


To change value of an element of a 2d array

In [28]:
a[1,6]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 20]]


To change series of number

In [29]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 20]]


In [30]:
a[:,2]=1,2
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 20]]


Creation of a 3d ARRAY

In [31]:
q=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(q)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


To get specific element

In [32]:
print(q[0,1,1]) # first matrix second row second element

4


In [33]:
print(q[:,1,:]) #both matrix second row ..to print both

[[3 4]
 [7 8]]


To Replace an element

In [34]:
#replace
q[:,1,:]=[9,9],[9,9] # replace both second rows of both matrix
q

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [9, 9]]])

Creation of All 0's matrix

In [35]:
#All 0's matrix-specifiy shape
a=np.zeros((2,2))
print(a)

print(np.zeros((2,2,3))) # vector of two matrices is 3D array
#vector is 1d

[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


Creation of All 1's matrix

In [36]:
print(np.ones((4,2,2),dtype='int32'))

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


To create a matrix of your choice


*   dtype='float32' :-specifies that the data type of the elements should be 32-bit floating-point numbers
*   This code creates a 2x2 NumPy array filled with the value 99



In [37]:
print(np.full((2,2),99,dtype='float32'))

[[99. 99.]
 [99. 99.]]


For reusing previous matrix

---
This code creates a new NumPy array with the same shape and data type as the existing array q, but fills it with the value 7.


In [38]:
print(np.full_like(q,7))

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


For creating matrix of random numbers

In [39]:
print(np.random.rand(2,3))
#creates an array of a given shape with random values between 0 and 1.
print('\n')
print(np.random.random_sample(q.shape))
#returns random floats in the half-open interval
print('\n')
print(np.random.randint(7,size=(3,3))) #generates 3*3 matrix of random numbers 0(include) to 7(exclude)

[[0.29659152 0.28347579 0.52196278]
 [0.76586472 0.42923579 0.07328042]]


[[[0.45825717 0.61131206]
  [0.62464073 0.31654827]]

 [[0.58185158 0.57922622]
  [0.41922938 0.2518823 ]]]


[[2 5 3]
 [4 2 4]
 [3 0 0]]


In [40]:
print(np.random.randint(-6,6,size=(2,2))) # generates 2*2 matrix of random numbers -6(include) to 6(exclude)
print('\n')
print(np.random.randint(-6,6,2)) # genrates 2 numbers of random numbers -6 to 6(exclude)
print('\n')

[[ 5  5]
 [-5 -1]]


[-3 -2]




To create an identity matrix (its is always a sqaure matrix)

In [41]:
print(np.identity(7,dtype='int16'))

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


Concept of Copying arrays

In [42]:
a=np.array([1,2,3])
b=a # a is created and then b is also pointing to same objects , a copy is not getting created its the same obj.
print(b)

b[0]=100
print(b)
print(a)

b=a.copy() # here the contents of a is copied in b
print(a)
b[2]=90
print(b)
print(a)

[1 2 3]
[100   2   3]
[100   2   3]
[100   2   3]
[100   2  90]
[100   2   3]


**Mathematics/Broadcasting In NumPy**

In [43]:
a=np.array([1,2,3,4])
print(a)

a+=2
print(a)
print(a+2)#add 2 to all elements of array
print(a-2)#subtract 2 from all elements of array
print(a*2)#multipy 2 to all elements of array
print(a/2)#divide all elements of array by 2

b=np.array([1,0,1,0])
print(a+b) # addition of two arrays

print(a**2)#square of all elements of array

[1 2 3 4]
[3 4 5 6]
[5 6 7 8]
[1 2 3 4]
[ 6  8 10 12]
[1.5 2.  2.5 3. ]
[4 4 6 6]
[ 9 16 25 36]


In [44]:
# to find the sin of all values
print(np.sin(a))

[ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [45]:
# to find the cos of all values
print(np.cos(a))

[-0.9899925  -0.65364362  0.28366219  0.96017029]


**Linear Algebra**

All 1's Matrix

In [46]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


The `np.full()` function is used to create a new NumPy array of a specified shape, filled with a constant value. This is useful when you need an array where every element is the same, rather than having to manually create and fill the array.

In [47]:
b=np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


Matrix Multiplication:

In [48]:
print(np.matmul(a,b)) #output would be 2 by 2 matrix

[[6. 6.]
 [6. 6.]]


 Find the determinant of a matrix
*   This code first creates a 3x3 identity matrix and assigns it to the variable c. Then, it calculates and prints the determinant of this identity matrix using np.linalg.det(c). The determinant of an identity matrix is always 1.



In [49]:
c=np.identity(3)
print(np.linalg.det(c))

1.0


**STATISTICS USING NUMPY**

In [50]:
stats=np.array([[5,2,3],[4,5,6]])
print(stats)

[[5 2 3]
 [4 5 6]]


In [51]:
print(np.max(stats,axis=1))
#Finds the maximum value in each row (axis=1) and prints a new array containing these maximum values

[5 6]


In [52]:
print(np.max(stats,axis=0))
#Finds the maximum value in each column (axis=0) and prints a new array containing these maximum values.

[5 5 6]


In [53]:
print(np.min(stats))
#Finds the minimum value in the entire array and prints it.

2


In [54]:
print(np.sum(stats))
#Calculates the sum of all elements in the array and prints it.

25


In [55]:
sum(sum(stats)) #same result as np.sum(stats) but is less efficient for NumPy arrays.
#Calculates the sum of all elements in the array by summing the sums of each inner list/row.

np.int64(25)